#!/usr/bin/env bash

set -o errexit
set -o pipefail

DC="${DC:-exec}"

# -----------------------------------------------------------------------------
# Helper functions start with _ and aren't listed in this script's help menu.
# -----------------------------------------------------------------------------

function _dc {
  docker-compose "${DC}" "${@}"
}

# -----------------------------------------------------------------------------

function start {
  docker-compose up --build -d
}

function cmd {
  # Run any command you want in the app container
  _dc app "${@}"
}

function lint:dockerfile {
  # Lint Dockerfile
  docker container run --rm -i \
    hadolint/hadolint hadolint --ignore DL3008 -t style "${@}" - < Dockerfile
}

function lint {
  # Lint Python code
  cmd flake8 "${@}"
}

function format:imports {
  # Sort Python imports
  cmd isort . "${@}"
}

function format {
  # Format Python code
  cmd black . "${@}"
}

function quality {
  # Perform all code quality commands together
  format:imports
  format
  lint
}


function test {
  # Run test suite
  cmd pytest test/ "${@}"
}

function test:coverage {
  # Get test coverage
  cmd pytest --cov test/ --cov-report term-missing "${@}"
}

function initdb {
  cmd flask db reset --with-testdb
  cmd flask db migrate
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

# This idea is heavily inspired by: https://github.com/adriancooney/Taskfile
TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
